# import "../fragment.gql"

mutation Login($input: LoginInput!) {
  login(input: $input) {
    ...UserInfo
    role
    boards {
      ...BoardInfo
      tasks {
        ...TaskInfo
        tags {
          ...TagInfo
        }
      }
    }
    createdAt
    updatedAt
  }
}

mutation Register($input: RegisterInput!) {
  register(input: $input) {
    ...UserInfo
    role
    boards {
      ...BoardInfo
      tasks {
        ...TaskInfo
        tags {
          ...TagInfo
        }
      }
    }
    createdAt
    updatedAt
  }
}

mutation Logout {
  logout
}

mutation ForgotPassword($email: String!) {
  forgotPassword(email: $email)
}

mutation ResetPassword($token: String!, $newPassword: String!) {
  resetPassword(token: $token, newPassword: $newPassword)
}

mutation ChangePassword($oldPassword: String!, $newPassword: String!) {
  changePassword(oldPassword: $oldPassword, newPassword: $newPassword)
}
