# import "../fragment.gql"

query Me {
  me {
    ...UserInfo
    role
    boards {
      ...BoardInfo
      tasks {
        ...TaskInfo
        tags {
          ...TagInfo
        }
      }
    }
    createdAt
    updatedAt
  }
}
