fragment UserInfo on User {
  id
  username
  email
}

fragment BoardInfo on Board {
  id
  name
  isArchived
}

fragment TaskInfo on Task {
  id
  name
  isCompleted
}

fragment TagInfo on Tag {
  id
  name
}
